# File: .github/workflows/main.yml

name: Run MLflow Model CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-mlflow-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install mlflow scikit-learn pandas

      - name: Navigate to MLflow Project directory and Run
        # Ketika langkah ini dimulai, working directory adalah root repositori (Eksperimen_SML_SRI-REJEKI/).
        # Kita perlu masuk ke 'Workflow-CI/' terlebih dahulu, lalu baru masuk ke 'MLProject/' di dalamnya.
        run: |
          # BARIS-BARIS INI AKAN DIJALANKAN SECARA BERURUTAN
          # Ini adalah langkah-langkah debugging, bisa dihapus setelah berhasil
          echo "Current working directory (should be root of repo): $(pwd)"
          ls -F
          
          # Pindah ke folder Workflow-CI
          cd Workflow-CI 
          
          echo "Changed directory to Workflow-CI: $(pwd)"
          ls -F
          
          # Lalu pindah ke folder MLProject di dalamnya
          cd MLProject
          
          echo "Changed directory to MLProject: $(pwd)"
          ls -F
          
          # Sekarang jalankan MLflow Project
          mlflow run . --no-conda