# File: .github/workflows/main.yml

name: Run MLflow Model CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-mlflow-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install MLflow CLI
        run: |
          python -m pip install --upgrade pip
          pip install mlflow

      # Perubahan KRITIS di sini: Gabungkan inisialisasi Conda dan jalankan MLflow
      # Gunakan langkah tunggal untuk memastikan Conda environment diinisialisasi
      # sebelum mlflow run mencoba mengaktifkannya.
      - name: Install Miniconda, Initialize Shell, and Run MLflow Project
        # Penting: Gunakan shell: bash untuk memastikan kita di bash
        shell: bash
        run: |
          # 1. Install Miniconda jika belum ada
          if ! command -v conda &> /dev/null
          then
              echo "Conda not found, installing Miniconda..."
              wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
              bash miniconda.sh -b -p $HOME/miniconda
              rm miniconda.sh
              # Ini inisialisasi Conda untuk sesi bash ini.
              # Perintah ini akan memodifikasi PATH untuk sesi ini.
              source $HOME/miniconda/etc/profile.d/conda.sh
              echo "Conda successfully installed and initialized."
          else
              echo "Conda is already installed."
              # Meskipun sudah ada, pastikan inisialisasi untuk sesi ini
              source $(conda info --base)/etc/profile.d/conda.sh
          fi

          # Opsional: Update Conda
          conda update -n base -c defaults conda || true

          # Navigasi ke direktori proyek MLflow Anda
          cd Workflow-CI/MLProject/

          # Debugging logs - sekarang Path sudah relatif dari working-directory ini
          echo "Listing contents of the MLflow Project directory (current working directory): $(pwd)"
          ls -F
          echo "---"

          # Verifikasi MLproject dan conda.yaml ada
          if [ -f "MLproject" ] && [ -f "conda.yaml" ]; then
            echo "MLproject and conda.yaml files found!"
            echo "--- MLproject content ---"
            cat MLproject
            echo "--- conda.yaml content ---"
            cat conda.yaml
            echo "---"
          else
            echo "Error: MLproject or conda.yaml file not found in the current directory!"
            exit 1
          fi

          # Jalankan MLflow project
          # Karena conda.sh sudah di-source, 'activate' akan dikenal oleh mlflow
          mlflow run .