# File: .github/workflows/main.yml

name: Run MLflow Model CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-mlflow-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Kita tetap set up Python utama di runner untuk menjalankan pip dan mlflow CLI
      # Tapi lingkungan untuk project MLflow akan dibuat berdasarkan conda.yaml
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      # Pastikan MLflow CLI terinstal di lingkungan utama
      - name: Install MLflow CLI
        run: |
          python -m pip install --upgrade pip
          pip install mlflow

      # Langkah ini akan memastikan Conda ada di runner agar MLflow bisa menggunakannya
      # Ini penting jika MLflow tidak menginstalnya secara otomatis
      - name: Install Miniconda if not present
        run: |
          # Periksa apakah conda sudah ada
          if ! command -v conda &> /dev/null
          then
              echo "Conda not found, installing Miniconda..."
              wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
              bash miniconda.sh -b -p $HOME/miniconda
              rm miniconda.sh
              echo "PATH=$HOME/miniconda/bin:$PATH" >> $GITHUB_ENV
              source $HOME/miniconda/bin/activate # Aktifkan base environment untuk perintah conda
          else
              echo "Conda is already installed."
          fi
          conda update -n base -c defaults conda || true # Update conda, izinkan gagal jika tidak ada update

      - name: Verify MLflow Project Directory and Run
        run: |
          echo "Listing contents of the MLflow Project directory (current working directory): $(pwd)"
          ls -F
          echo "---"

          # Pastikan MLproject dan conda.yaml ada
          if [ -f "MLproject" ] && [ -f "conda.yaml" ]; then
            echo "MLproject and conda.yaml files found!"
            echo "--- MLproject content ---"
            cat MLproject
            echo "--- conda.yaml content ---"
            cat conda.yaml
            echo "---"
          else
            echo "Error: MLproject or conda.yaml file not found in the current directory!"
            exit 1
          fi

          # JALANKAN MLflow TANPA ARGUMEN --no-conda atau --env-manager
          # MLflow akan otomatis mendeteksi dan menggunakan conda.yaml Anda
          mlflow run .

        working-directory: Workflow-CI/MLProject # Ini sudah benar