# File: .github/workflows/main.yml

name: Run MLflow Model CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-mlflow-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install MLflow CLI
        run: |
          python -m pip install --upgrade pip
          pip install mlflow

      # Perubahan Utama di sini: Gunakan cara inisialisasi conda yang lebih robust
      - name: Install Miniconda and Initialize Shell
        run: |
          # Periksa apakah conda sudah ada
          if ! command -v conda &> /dev/null
          then
              echo "Conda not found, installing Miniconda..."
              wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
              bash miniconda.sh -b -p $HOME/miniconda
              rm miniconda.sh
              # Ini penting: Inisialisasi conda untuk bash agar 'activate' dikenali
              # Ini akan memodifikasi .bashrc atau .profile, tapi kita perlu memuatnya
              $HOME/miniconda/bin/conda init bash
          else
              echo "Conda is already installed."
          fi
          # Perintah ini untuk memastikan conda base environment diupdate, izinkan gagal
          conda update -n base -c defaults conda || true
        # Penting: Gunakan shell: bash -l (login shell) untuk langkah-langkah berikutnya
        # Ini akan memuat file inisialisasi seperti .bashrc atau .profile
        shell: bash

      # Ubah langkah Verify MLflow Project Directory and Run agar menggunakan shell yang diinisialisasi
      - name: Verify MLflow Project Directory and Run
        run: |
          # Debugging logs sudah benar
          echo "Listing contents of the MLflow Project directory (current working directory): $(pwd)"
          ls -F
          echo "---"

          if [ -f "MLproject" ] && [ -f "conda.yaml" ]; then
            echo "MLproject and conda.yaml files found!"
            echo "--- MLproject content ---"
            cat MLproject
            echo "--- conda.yaml content ---"
            cat conda.yaml
            echo "---"
          else
            echo "Error: MLproject or conda.yaml file not found in the current directory!"
            exit 1
          fi

          # Jalankan MLflow project
          mlflow run .

        working-directory: Workflow-CI/MLProject
        # Penting: Gunakan shell: bash -l (login shell) di sini juga
        # agar lingkungan conda bisa diaktifkan oleh mlflow run
        shell: bash -l # "-l" untuk memastikan itu adalah login shell