name: Run MLflow Model CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write  # Berikan izin push ke repo

jobs:
  run-mlflow-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow scikit-learn pandas numpy

      - name: Run MLflow project
        working-directory: ./Workflow-CI/MLProject
        run: |
          mlflow run .

      - name: Commit MLflow artifacts to GitHub
        if: success()
        working-directory: ./Workflow-CI/MLProject
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add -f mlruns/
          if [[ -n $(git status --porcelain) ]]; then
            git commit -m "Add MLflow artifacts from workflow run"
            git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
            git push origin main
          else
            echo "No changes in mlruns to commit."
          fi
