# File: .github/workflows/main.yml

name: Run MLflow Model CI

on:
  push:
    branches:
      - main # Sesuaikan dengan cabang Anda (main)
  workflow_dispatch:

jobs:
  run-mlflow-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (full history to avoid cache issues)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ambil seluruh riwayat

      - name: Set up Python 3.9 # Gunakan Python 3.9 sesuai conda.yaml Anda
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: 'pip' # Caching pip tetap bermanfaat

      - name: Install all dependencies # Instal SEMUA dependensi proyek Anda dengan pip
        run: |
          set -x # Debugging
          python -m pip install --upgrade pip
          # Pastikan semua library dari modelling.py dan conda.yaml Anda diinstal di sini
          # (pandas, scikit-learn, mlflow, numpy, dll.)
          pip install pandas scikit-learn mlflow numpy # Tambahkan numpy jika modelling.py menggunakannya

      # Langkah ini diganti dengan pendekatan sederhana, mirip teman Anda
      - name: Verify MLflow Project Directory and Run
        shell: bash
        run: |
          set -x # Debugging

          # Navigasi ke direktori proyek MLflow Anda
          cd Workflow-CI/MLProject/

          # Debugging logs
          echo "Listing contents of the MLflow Project directory (current working directory): $(pwd)"
          ls -F
          echo "---"

          # Hapus dan download ulang CSV untuk memastikan bersih (tetap kita pakai)
          echo "Attempting to remove potentially cached/corrupted CSV file in runner..."
          rm -f wine_quality_preprocessing/wine_quality_preprocessed.csv || true
          echo "Removed. Now trying to re-download the clean version from GitHub raw."

          RAW_CSV_URL="https://raw.githubusercontent.com/SriRejeki1510/Eksperimen_SML_SRI-REJEKI/main/Workflow-CI/MLProject/wine_quality_preprocessing/wine_quality_preprocessed.csv"
          
          mkdir -p wine_quality_preprocessing/

          echo "Downloading clean CSV from $RAW_CSV_URL..."
          wget -q $RAW_CSV_URL -O wine_quality_preprocessing/wine_quality_preprocessed.csv
          
          ls -lh wine_quality_preprocessing/wine_quality_preprocessed.csv

          # Verifikasi ISI FILE CSV DI RUNTIME ACTIONS - Ini akan menunjukkan apa yang sedang dibaca!
          echo "Verifying content of wine_quality_preprocessed.csv at line 1360-1365 (after re-download):"
          sed -n '1360,1365p' wine_quality_preprocessing/wine_quality_preprocessed.csv || true
          echo "--- End of verification ---"


          # Verifikasi MLproject ada
          if [ -f "MLproject" ]; then # Tidak perlu cek conda.yaml karena kita tidak pakai itu untuk env
            echo "MLproject file found!"
            echo "--- MLproject content ---"
            cat MLproject
            echo "---"
          else
            echo "Error: MLproject file not found in the current directory!"
            exit 1
          fi

          # Ini adalah perubahan kunci: Gunakan --env-manager=local seperti teman Anda
          # dan pastikan MLFLOW_TRACKING_URI diatur
          export MLFLOW_TRACKING_URI=./mlruns
          echo "MLFLOW_TRACKING_URI set to: $MLFLOW_TRACKING_URI"
          
          mlflow run . --env-manager=local # PERUBAHAN UTAMA DI SINI