name: Run MLflow Model

on:
  push:
    branches:
      - main

jobs:
  run-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install mlflow pandas scikit-learn

      - name: Run MLflow Project
        run: |
          cd MLProject
          mlflow run . --no-conda
