name: Run MLflow Model CI 

on:
  push:
    branches:
      - main 
  workflow_dispatch: 

jobs:
  run-mlflow-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install dependencies
        run: |
          # Upgrade pip ke versi terbaru
          python -m pip install --upgrade pip
          # Instal semua paket yang diperlukan untuk proyek MLflow Anda
          # Pastikan daftar ini mencakup semua yang terdaftar dalam file environment MLproject Anda
          pip install mlflow scikit-learn pandas # Tambahkan dependensi spesifik lainnya di sini!

      - name: Verify MLflow Project Directory and Run
        run: |
          # Opsional: Debugging - tampilkan isi direktori saat ini (yang merupakan root repo)
          echo "Listing contents of repository root (current working directory): $(pwd)"
          ls -F
          echo "---"
          
          # Opsional: Debugging - tampilkan isi direktori proyek MLflow yang diharapkan
          echo "Listing contents of Workflow-CI/MLProject:"
          ls -F Workflow-CI/MLProject
          echo "---"

          # Verifikasi apakah file MLproject ada sebelum mencoba menjalankannya
          if [ -f "Workflow-CI/MLProject/MLproject" ]; then
            echo "MLproject file found in Workflow-CI/MLProject!"
            cat Workflow-CI/MLProject/MLproject # Tampilkan isi file untuk debugging
          else
            echo "Error: MLproject file not found in Workflow-CI/MLProject!"
            exit 1 # Gagal workflow jika file tidak ditemukan
          fi
          
          # Sekarang jalankan Proyek MLflow. Kunci 'working-directory' memastikan
          # perintah 'mlflow run .' dieksekusi dari lokasi yang benar.
          mlflow run . --no-conda # Gunakan --no-conda jika Anda mengelola dependensi langsung dengan pip
        
        working-directory: Workflow-CI/MLProject