name: Run MLflow Model

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install mlflow scikit-learn pandas

      - name: Run MLflow Project
        run: |
          cd Workflow-CI
          mlflow run . --no-conda
