# File: .github/workflows/main.yml

name: Run MLflow Model CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-mlflow-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Saya sangat menyarankan membuat requirements.txt di Workflow-CI/MLProject/
          # pip install -r requirements.txt
          # Atau tetap pakai ini jika belum ada requirements.txt
          pip install mlflow scikit-learn pandas

      - name: Verify MLflow Project Directory and Run
        run: |
          # Perintah ls -F di sini akan menampilkan isi working-directory saat ini
          # yang sudah kita set ke 'Workflow-CI/MLProject'
          echo "Listing contents of the MLflow Project directory (current working directory): $(pwd)"
          ls -F
          echo "---"

          # Kita tidak perlu lagi mencari 'Workflow-CI/MLProject' karena kita sudah di dalamnya
          # Hapus atau komentar baris ini:
          # echo "Listing contents of Workflow-CI/MLProject:"
          # ls -F Workflow-CI/MLProject
          # echo "---"

          # Verifikasi apakah file MLproject ada di direktori saat ini
          # (yaitu Workflow-CI/MLProject/)
          if [ -f "MLproject" ]; then # Cukup cek "MLproject" saja, bukan "Workflow-CI/MLProject/MLproject"
            echo "MLproject file found!"
            cat MLproject # Cukup cat "MLproject" saja
          else
            echo "Error: MLproject file not found in the current directory!"
            exit 1
          fi

          mlflow run . --no-conda

        working-directory: Workflow-CI/MLProject # Ini sudah benar